name: skatesplugin
main: com.drforse.skatesplugin.SkatesPlugin
version: 1.0-SNAPSHOT
api-version: 1.16

permissions:
  skatesplugin.op:
    description: allows you to execute commands of the scates plugin
    default: op

commands:
  setWalkSpeed:
    description: command to set walk speed
    usage: /setWalkSpeed [player] [float]
    permission: skatesplugin.op
    permission-message: You don't have <permission>

  getWalkSpeed:
    description: command to get walk speed
    usage: /getWalkSpeed [player] [float]
    permission: skatesplugin.op
    permission-message: You don't have <permission>