name: skatesplugin
main: com.drforse.skatesplugin.SkatesPlugin
version: 1.0-SNAPSHOT
api-version: 1.16

permissions:
  skatesplugin.op:
    description: allows you to execute commands of the scates plugin
    default: op

commands:
  setWalkSpeed:
    description: command to set walk speed
    usage: /<command> [player] [float]
    permission: <plugin name>.op
    permission-message: You don't have <permission>